build: Stop execution if make fails
Signed-off-by: Nirmoy Das <nirmoy.aiemd@gmail.com>
Signed-off-by: Avi Kivity <avi@cloudius-systems.com>

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -24,6 +24,12 @@ do
 	esac
 done
 make "${args[@]}" | tee build.out
+# check exit status of make
+if [ ${PIPESTATUS[0]} -ne 0 ]
+then
+    echo "make failed. Exiting from build script"
+    exit
+fi
 
 for i
 do
